/* Copyright (c) 2023, Sascha Willems
 *
 * SPDX-License-Identifier: MIT
 *
 */
#version 460


#include "shaderInclude.glsl"
#include "random.glsl"
layout(location = 3) rayPayloadInEXT uint payloadSeed;

void main()
{
	uint primitiveID = gl_PrimitiveID;
	uint clusterID = gl_ClusterIDNV_;
	Triangle tri = unpackTriangle(gl_InstanceID, clusterID, primitiveID);
	GeometryNode geometryNode = geometryNodes.nodes[gl_InstanceID];
	ClusterRT cluster = sceneClusters.clusters[geometryNode.clusterStartOffset + clusterID];

	// offset from all scene's triangles
	uint triOffsetGlobal = geometryNode.triangleStartOffset + cluster.firstTriangle + primitiveID;

	// find primitive Index
	uint primitiveIdx = 0;
	for (uint i = 0; i < pushData.numPrimitives; ++i)
	{
		if (triOffsetGlobal >= meshPrimitives.primitives[i].triangleStartOffsetGlobal)
			primitiveIdx = i;
		else
			break;
	}

	ClusteredMeshPrimitive meshPrimitive = meshPrimitives.primitives[primitiveIdx];

	vec4 color = texture(textures[nonuniformEXT(meshPrimitive.textureIndexBaseColor)], tri.uv);


//	ClusteredMeshPrimitive meshPrimitive = meshPrimitives.primitives[1];
//	vec4 color = texture(textures[nonuniformEXT(meshPrimitive.textureIndexBaseColor)], tri.uv);


	// If the alpha value of the texture at the current UV coordinates is below a given threshold, we'll ignore this intersection
	// That way ray traversal will be stopped and the miss shader will be invoked
	if (color.a < 0.9) {
		if(rnd(payloadSeed) > color.a) {
			ignoreIntersectionEXT;
		}
	}
}