#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require

#include "../../../MyDevs/myBase/myIncludesCPUGPU.h"

#define VERTEX_SIZE 112
#define NUM_VEC4_FROM_VERTEX_SIZE (VERTEX_SIZE / 16)

// Specialization Constant
layout(constant_id = 0) const uint32_t NUM_MESHES = 1;


layout(buffer_reference, scalar) buffer Vertices {vec4 v[]; };
layout(push_constant) uniform pushConstant {
	uint64_t vertexBuffer;
	uint32_t numVertices; // total
} pushConstantData;

struct JointData 
{
	mat4 matrix;
	mat4 jointMatrices[64*4];
};

layout(binding = 0, set = 0, scalar) buffer StorageData
{
	JointData jointData[];
}storageData;

layout(binding = 1, set = 1, scalar) buffer DeformedVertices
{
	vec4 v[];
}deformedVertices;
layout(binding = 2, set = 1, scalar) uniform UniformData
{
	uvec4 numMeshVertices[6];
//	uvec4 numMeshVertices[NUM_MESHES];
}uniformData;

layout(local_size_x = SKINNING_WORK_GROUP_SIZE, local_size_y = 1, local_size_z = 1) in;
void main()	
{
	uint32_t threadIdxGlobal = gl_GlobalInvocationID.x;
	if (threadIdxGlobal > pushConstantData.numVertices)
		return;
	Vertices tPoseVertices = Vertices(pushConstantData.vertexBuffer);	
	uint32_t meshID = floatBitsToUint(tPoseVertices.v[threadIdxGlobal * NUM_VEC4_FROM_VERTEX_SIZE + 6].x);
//	uint32_t numMeshVertices = uniformData.numMeshVertices[meshID].x;


	JointData jointData = storageData.jointData[meshID];
	
	vec4 vertexPos = tPoseVertices.v[threadIdxGlobal * NUM_VEC4_FROM_VERTEX_SIZE + 0];
	vec4 vertexNorm = vec4(0);
	vertexNorm.x = vertexPos.w;
	vertexPos.w = 1.f;
	vertexNorm.yz = tPoseVertices.v[threadIdxGlobal * NUM_VEC4_FROM_VERTEX_SIZE + 1].xy;
	vec4 vertexJoint0 = tPoseVertices.v[threadIdxGlobal * NUM_VEC4_FROM_VERTEX_SIZE + 4];
	vec4 vertexWeight0 = tPoseVertices.v[threadIdxGlobal * NUM_VEC4_FROM_VERTEX_SIZE + 5];

	mat4 skinMat = 
		vertexWeight0.x * jointData.jointMatrices[int(vertexJoint0.x)] +
		vertexWeight0.y * jointData.jointMatrices[int(vertexJoint0.y)] +
		vertexWeight0.z * jointData.jointMatrices[int(vertexJoint0.z)] +
		vertexWeight0.w * jointData.jointMatrices[int(vertexJoint0.w)];

//	vec3 deformedPos = (skinMat * vertexPos).xyz;
	// bindSpace -> JointRoot(Mesh's Local) -> Mesh's World
	vec3 deformedPos = (jointData.matrix * skinMat * vertexPos).xyz;
	vec3 deformedNorm = (transpose(inverse(skinMat)) * vertexNorm).xyz; 

	// write into ssbo
	// pos
	deformedVertices.v[(threadIdxGlobal) * NUM_VEC4_FROM_VERTEX_SIZE + 0].xyz = deformedPos;
	// normal
	deformedVertices.v[(threadIdxGlobal) * NUM_VEC4_FROM_VERTEX_SIZE + 0].w = deformedNorm.x;
	deformedVertices.v[(threadIdxGlobal) * NUM_VEC4_FROM_VERTEX_SIZE + 1].xy = deformedNorm.yz;

}